export const TRANSLATION_START = 'TRANSLATION_START';
export const TRANSLATION_SUCCESS = 'TRANSLATION_SUCCESS';
export const TRANSLATION_FAIL = 'TRANSLATION_FAIL';

export const SET_TRANSLATION_DATA = 'SET_TRANSLATION_DATA';
