export const TRANSLATION_START = 'TRANSLATION_START';
export const TRANSLATION_SUCCESS = 'TRANSLATION_SUCCESS';
export const TRANSLATION_FAIL = 'TRANSLATION_FAIL';

export const SET_TRANSLATION_DATA = 'SET_TRANSLATION_DATA';

// Banks

export const GET_BANKS_DATA_START = 'GET_BANKS_DATA_START';
export const GET_BANKS_DATA_SUCCESS = 'GET_BANKS_DATA_SUCCESS';
export const GET_BANKS_DATA_FAIL = 'GET_BANKS_DATA_FAIL';

export const SET_BANKS_DATA = 'SET_BANKS_DATA';
